spring.application.name=backend
server.port=8080

spring.data.mongodb.uri=${MONGODB_URI}

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

groq.api.key=${GROQ_API_KEY}

spring.web.cors.allowed-origins=${FRONTEND_URL}